const API_KEY = process.env.GHN_TOKEN;
const API_URL = process.env.GHN_API_URL;
const SHOP_ID = process.env.GHN_SHOP_ID;
const FROM_DISTRICT_ID = process.env.GHN_FROM_DISTRICT_ID;
const FROM_WARD_ID = process.env.GHN_FROM_WARD_ID;
const SERVICE_ID = process.env.GHN_SERVICE_ID;
const SERVICE_TYPE_ID = process.env.GHN_SERVICE_TYPE_ID;
const DEFAULT_WEIGHT = process.env.GHN_DEFAULT_WEIGHT;
const DEFAULT_LENGTH = process.env.GHN_DEFAULT_LENGTH;
const DEFAULT_WIDTH = process.env.GHN_DEFAULT_WIDTH;
const DEFAULT_HEIGHT = process.env.GHN_DEFAULT_HEIGHT;
const FALLBACK_FEE = process.env.GHN_FALLBACK_FEE;

export { API_KEY, API_URL, SHOP_ID, FROM_DISTRICT_ID, FROM_WARD_ID, SERVICE_ID, SERVICE_TYPE_ID, DEFAULT_WEIGHT, DEFAULT_LENGTH, DEFAULT_WIDTH, DEFAULT_HEIGHT, FALLBACK_FEE }